[build]
  # Install dependencies including devDependencies so `tsc` (from devDependencies) is available
  command = "npm ci --include=dev && npm run build"
  publish = "dist"

[context.production.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  # Do not force rewrite all requests — allow Netlify to serve existing static assets
